### PR TITLE
[#1] Allow configuration of server certificates

### LINKED ISSUE #1: UnknownHostKey - can not fetch host-key from the injected gateway
Hello @abdallahghdiri,

I'm having some troubles when using your library, I'm unable to connect from my production code because a new host-key is generated every time. Since there is no way (yet) to fetch it the connection fails.

Would you be open to a PR which will solve that?

Thanks a lot!

### PR DESCRIPTION
**Pull request by martinvw**
Fixes #1

Signed-off-by: Martin van Wingerden <martin@martinvw.nl>

### CODE REVIEW

**Review by abdallahghdiri — CHANGES_REQUESTED** [review]
Hello,

Thank you for your contribution 

Can you please keep the following [test](https://github.com/abdallahghdiri/junit5-dummy-sftp-server/pull/2/commits/c5bb8b6619ed558b79bc64672cd27c0eb0321a01#diff-cb8ec522454b1707758bb666ed566c59) simple as it was and move checking the host key to a separate one.

**Comment by martinvw** [comment]
Thanks for your feedback!

I moved the changed parts for the test to `DummySftpHostKeyTest`. 

Please let me know if you require any other changes.

**Comment by martinvw** [comment]
@abdallahghdiri any updates about this?

**Comment by abdallahghdiri** [comment]
@martinvw i do not yet see my requested changes in a in a new commit

**Comment by martinvw** [comment]
I updated the old commit and force pushed so there is a still one commit but it includes the requested changes. Sorry for the confusion. 

I aimed to keep your project's history clean 😊

**Comment by abdallahghdiri** [comment]
Ok great thank you i'll add some documentation and approve this PR

**Comment by abdallahghdiri** [comment]
@martinvw i will include this feature in the **0.3.0** release

**Comment by martinvw** [comment]
Great, thanks a lot!

**Pull request merged**
